# Generated by Django 5.0.6 on 2024-05-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HautFait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('xp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('game_image', models.ImageField(blank=True, null=True, upload_to='game_images/')),
                ('categorie', models.CharField(choices=[('ACT', 'Action'), ('SPO', 'Sport'), ('RPG', 'Rpg'), ('RTS', 'Rts'), ('FPS', 'Fps'), ('MOB', 'Moba'), ('PAR', 'Party'), ('SIM', 'Simulation'), ('ARC', 'Arcade'), ('COM', 'Combat'), ('SAN', 'Sandbox'), ('AVE', 'Aventure'), ('GES', 'Gestion'), ('AUT', 'Autres')], max_length=3)),
                ('type_jeu', models.CharField(choices=[('solo', 'Solo'), ('equipe', 'Equipe')], default='equipe', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_joueur1', models.IntegerField(blank=True, null=True)),
                ('score_joueur2', models.IntegerField(blank=True, null=True)),
                ('score_equipe1', models.IntegerField(blank=True, null=True)),
                ('score_equipe2', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
