# Generated by Django 5.0.6 on 2024-05-25 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='joueurs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partie',
            name='equipe1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties_equipe1', to='application.equipe'),
        ),
        migrations.AddField(
            model_name='partie',
            name='equipe2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties_equipe2', to='application.equipe'),
        ),
        migrations.AddField(
            model_name='partie',
            name='jeu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.jeu'),
        ),
        migrations.AddField(
            model_name='partie',
            name='joueur1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties_joueur1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partie',
            name='joueur2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties_joueur2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partie',
            name='vainqueur_equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties_gagnees_equipe', to='application.equipe'),
        ),
        migrations.AddField(
            model_name='partie',
            name='vainqueur_joueur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parties_gagnees_joueur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournoi',
            name='jeux',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournois_jeux', to='application.jeu'),
        ),
        migrations.AddField(
            model_name='tournoi',
            name='jeuxpool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournois_jeuxpool', to='application.jeu'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='tournoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.tournoi'),
        ),
        migrations.AddField(
            model_name='vote',
            name='jeu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.jeu'),
        ),
        migrations.AddField(
            model_name='vote',
            name='joueur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='tournoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.tournoi'),
        ),
    ]
