# Generated by Django 5.0.6 on 2024-05-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeu',
            name='lien',
            field=models.URLField(blank=True, null=True),
        ),
    ]
