# Generated by Django 5.0.6 on 2024-05-25 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_jeu_lien'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournoi',
            name='joueurs_inscrits',
            field=models.ManyToManyField(blank=True, related_name='tournois_inscrits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournoi',
            name='joueurs_selectionnes',
            field=models.ManyToManyField(blank=True, related_name='tournois_selectionnes', to=settings.AUTH_USER_MODEL),
        ),
    ]
