# Generated by Django 5.0.6 on 2024-05-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_tournoi_joueurs_inscrits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournoi',
            name='type_tournoi',
            field=models.CharField(choices=[('online', 'En ligne'), ('offline', 'En présentiel')], default='online', max_length=7),
        ),
    ]
