# Generated by Django 5.0.6 on 2024-05-25 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_tournoi_type_tournoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='jeux',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournois_jeux', to='application.jeu'),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='jeuxpool',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournois_jeuxpool', to='application.jeu'),
        ),
    ]
