# Generated by Django 5.0.6 on 2024-05-25 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_tournoi_jeux_alter_tournoi_jeuxpool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='jeux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournois_jeux', to='application.jeu'),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='jeuxpool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournois_jeuxpool', to='application.jeu'),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='joueurs_inscrits',
            field=models.ManyToManyField(blank=True, null=True, related_name='tournois_inscrits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='joueurs_selectionnes',
            field=models.ManyToManyField(blank=True, null=True, related_name='tournois_selectionnes', to=settings.AUTH_USER_MODEL),
        ),
    ]
