# Generated by Django 5.0.6 on 2024-05-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_tournoi_jeux_alter_tournoi_jeuxpool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournoi',
            name='jeux',
        ),
        migrations.RemoveField(
            model_name='tournoi',
            name='jeuxpool',
        ),
        migrations.AddField(
            model_name='tournoi',
            name='jeux',
            field=models.ManyToManyField(blank=True, related_name='tournois_jeux', to='application.jeu'),
        ),
        migrations.AddField(
            model_name='tournoi',
            name='jeuxpool',
            field=models.ManyToManyField(blank=True, related_name='tournois_jeuxpool', to='application.jeu'),
        ),
    ]
