# Generated by Django 4.2.13 on 2024-05-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='matchs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='tournois',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joueur',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
